# Technical Indicator Configuration
# These are the exact settings used during backtesting
# Match what the LLMs saw when making trading decisions

# Data interval for OHLC candles
data_interval: '4h'

# EMA (Exponential Moving Average) - Trend identification
ema_periods: [20, 50]

# RSI (Relative Strength Index) - Overbought/oversold conditions
rsi_periods: [7, 14]

# ATR (Average True Range) - Volatility measurement
atr_periods: [3, 14]

# MACD (Moving Average Convergence Divergence) - Momentum and trend changes
macd:
  fast: 12
  slow: 26
  signal: 9
